#!/bin/bash

APP_ANDROID_NAME=""
APP_ANDROID_VERSION=""
APP_ANDROID_BUILD_NUMBER=""
APP_ANDROID_BUNDLE_ID=""
APP_ANDROID_PACKAGE=""
APP_ANDROID_SCHEME=""

MONERO_COM="monero.com"
CAKEWALLET="cakewallet"
XCASHLABS="xcashlabs"

TYPES=($MONERO_COM $CAKEWALLET $XCASHLABS)
APP_ANDROID_TYPE=$1

MONERO_COM_NAME="Monero.com"
MONERO_COM_VERSION="5.9.0"
MONERO_COM_BUILD_NUMBER=4152
MONERO_COM_BUNDLE_ID="com.monero.app"
MONERO_COM_PACKAGE="com.monero.app"
MONERO_COM_SCHEME="monero.com"

CAKEWALLET_NAME="Cake Wallet"
CAKEWALLET_VERSION="5.9.0"
CAKEWALLET_BUILD_NUMBER=4305
CAKEWALLET_BUNDLE_ID="com.cakewallet.cake_wallet"
CAKEWALLET_PACKAGE="com.cakewallet.cake_wallet"
CAKEWALLET_SCHEME="cakewallet"

XCASHLABS_NAME="XCash Klassic"
XCASHLABS_VERSION="5.9.0"
XCASHLABS_BUILD_NUMBER=1
XCASHLABS_BUNDLE_ID="org.xcashlabs.wallet"
XCASHLABS_PACKAGE="org.xcashlabs.wallet"
XCASHLABS_SCHEME="xcashlabs"

if ! [[ " ${TYPES[*]} " =~ " ${APP_ANDROID_TYPE} " ]]; then
    echo "Wrong app type."
    return 1 2>/dev/null
    exit 1
fi

case $APP_ANDROID_TYPE in
    $MONERO_COM)
        APP_ANDROID_NAME=$MONERO_COM_NAME
        APP_ANDROID_VERSION=$MONERO_COM_VERSION
        APP_ANDROID_BUILD_NUMBER=$MONERO_COM_BUILD_NUMBER
        APP_ANDROID_BUNDLE_ID=$MONERO_COM_BUNDLE_ID
        APP_ANDROID_PACKAGE=$MONERO_COM_PACKAGE
        APP_ANDROID_SCHEME=$MONERO_COM_SCHEME
        ;;
    $CAKEWALLET)
        APP_ANDROID_NAME=$CAKEWALLET_NAME
        APP_ANDROID_VERSION=$CAKEWALLET_VERSION
        APP_ANDROID_BUILD_NUMBER=$CAKEWALLET_BUILD_NUMBER
        APP_ANDROID_BUNDLE_ID=$CAKEWALLET_BUNDLE_ID
        APP_ANDROID_PACKAGE=$CAKEWALLET_PACKAGE
        APP_ANDROID_SCHEME=$CAKEWALLET_SCHEME
        ;;
    $XCASHLABS)
        APP_ANDROID_NAME=$XCASHLABS_NAME
        APP_ANDROID_VERSION=$XCASHLABS_VERSION
        APP_ANDROID_BUILD_NUMBER=$XCASHLABS_BUILD_NUMBER
        APP_ANDROID_BUNDLE_ID=$XCASHLABS_BUNDLE_ID
        APP_ANDROID_PACKAGE=$XCASHLABS_PACKAGE
        APP_ANDROID_SCHEME=$XCASHLABS_SCHEME
        ;;
esac

export APP_ANDROID_TYPE
export APP_ANDROID_NAME
export APP_ANDROID_VERSION
export APP_ANDROID_BUILD_NUMBER
export APP_ANDROID_BUNDLE_ID
export APP_ANDROID_PACKAGE
export APP_ANDROID_SCHEME